import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import SiteShell from "./components/SiteShell";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full overflow-hidden overscroll-none antialiased`}
    >
      <body className="h-full overflow-hidden overscroll-none bg-neutral-50 font-sans text-neutral-950">
        <SiteShell>{children}</SiteShell>
      </body>
    </html>
  );
}
